server:
  port: 8080


jwt:
  access:
    token:
      secret: U0RGVyQ0MzUzZnNkRyUkXiQlXjxERkhHPE9ZVUslJF4+SkhGR0pUUllVJV4=
      expiry:
        adding:
          amount: 2
  refresh:
    token:
      secret: c2RGJF4lJiVeKERGR05NU0RGR0xFRktHREZMT0pUIylUIyQlXiMkJV9eJCVe
      expiry:
        adding:
          amount: 10

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  security:
    user:
      name: "1122"
      password: "1122"

telegram:
  bot:
    path: "/webhook"
    username: "info_salary_bot"
    token: "7836600588:AAF72cif-47HaWEfg8vYF9bPd5ymHmVlKjg"
    webhook-url: "https://df57-213-230-86-114.ngrok-free.app/webhook"

notion:
  database:
    version: "2022-06-28"
    id: "17791cb8af44809aa050ce4728458b4d"
    token: "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"
    base-url: "https://api.notion.com/v1"

springdoc:
  swagger-ui:
    try-it-out-enabled: on


